; generated by PrusaSlicer 2.5.0+win64 on 2022-10-31 at 22:19:56 UTC


;
; thumbnail begin 160x120 13312
; iVBORw0KGgoAAAANSUhEUgAAAKAAAAB4CAYAAAB1ovlvAAAmxklEQVR4Ae2d93tU15nH9VM2m012vX
; GceP3YFBswmG7ASEioIapoxlQXDJgiIUQXAgFGFDfsYLBNvHGcTeI4zSabOMXxOkUuieNNdpPskye7
; +W/uns+553vvO1ejYmKaOOd57jPSzOhq5sznft96zlRUxBFHHHHEEUccccQRRxxxxBFHHHHEEUcccc
; QRRxxxxBFHHHHEEUccccQRRxxxxBFHHHHEEUccccQRRxxxxBFHHHHEEUccccQRRxxxxBFHHB//uOPG
; T9Vz3P7ZT9VXxBHHpR7N4z7fvbd2ZM+XV05IXl49Mfm3cLy8amLyr/dNSJ5fflfSXjO8Z/PMW3tGRi
; jj+DjGonE3dS8b/4Xur6+dlHz7gSnJ9x6cklxYP7XkeP2hqcl33f3fun9ywvO+siqFsaVqWAQxjosb
; oz/3D/XLJ3yh+5sOKKD794fvTt7YOC358aZpyU8fmZ68uTk9+Jn7fuQe+8GGu5PXHZDfcaACIkp5bt
; m4ZMvM23qG//Pf11fEEcdgxrLxn+/+hgPoOwG8Hzu4fuZg+48tM5K3t96T/GJbevzSHT/fyjHDPwaM
; gMjfAO03101OvupM9Av3jk+eXHRnUnv7Z7sr4oijv4HqvepM6esPTUne2DAtefORFDyA+1XLzKSn1R
; 3u9t1wy/GrlhzGtzajiNO9Gr72UCmETzgI7596S09FHHGUG/vrR/Z8+4HJ3q97I6geUAHeOw6491or
; k/e3VybvcbTmtzwGhDzvbaeG/N2PN05PldBB+IqD8CvOHJ915vixhWOStVP+JUIYR+kg0CCIuLA+9f
; XeDPBJ7QDv1zsqk9+Eg59/3ZYe7wUoeR5K+LZTTP6e83zfnc/7hGsmuUh5fPLs0nHJsbmjkpWTbo4Q
; xpGOJXd9vhtTSQDxQ2d2f+JMKEqGqgEVkAHdB+1VyW/N8cGOqhTGtlwZARZz/daW6f48mOLMH3TpGq
; JjTPGhxtuTe4bd0F0Rx/U9xtz0D/WoE5D8IAQcbzkFQ8neCcoHZAD3oTv+c+escFgQU0UEwHdaggpu
; TYMSVPBCUMGvuf/z4orxyTOLxybd80Yne2pHJNNu/afuijiu33Gg/vae1PTm6kfQYdUPpfvQQfc7jl
; 3hCCB6AN2RARj8QaJlfEGi4u87sImoSc2QsMYXPLVgTHLQqeD2WcOSijiuz0FlA/X7bki3/Kjg+70X
; /L7ftjvYdlUnv99dk/wXx54a93O1B/HDACEq+b4BkHO8uTlPywAgqZ2XXDDyXDDDR5pGJbtmj0imRx
; W8PgcwkHJ5zVUyBCCqhQ8nAH/j1a/aQTc7+cO+uuRPHfXJH93tf7vfARIAPygDoKJhKSCQv7Jukivb
; pVWSp5rv9MHIvrqRTgWHRxW83saisTd1f23NRFc+m+JLab7SEfJ+vzAK+IFTv9/tnp38cX9D8ueDTc
; lfuua52znu9/oAYLU30Zjqd0MQgg+oxPQbFsBQpnsuAIgf6FyAZEf18KiC19s474IBfDKCA6JfolV8
; QKBJI+CZHqjfOAB/v7cu+R8H3/8eXZj89dFFyV8Oz0/+dKDRqWJt8lsHICpZNL+o309ciY5zAjh1ZG
; uCTzsAT8wfnXQ23J7srBmRtEYVvH4GdV7qtK+snezBoGKBSgEhQchbwQy/45LMv0YBPYBzk/9z8P31
; WLMDcEHyRwcgyohCvu/Vb2aJ+vlk9KZQH3YAEuj4KNjlAs8FAI87AA813pHsdn5gVMHraLgPuwdfDE
; X6tjPBVCuIgn0aZlPaZCAVfG+HCzR21yZ/ODAn+XPXfH/8qbPJqWK9U7+a5H2nfu+25qb37VAXBmTU
; j/N+N8sDTki+5JSXKBgTfNyZYCJhAGyvGU73TFTB62GcW3aX7+EDQHxAAHk9tFbhs2GGSST7YITyW3
; t18uGeuuT3+xr8AZAfOPjec/Chkr8K8Mn0yvez6qc2rfP3ptUQomB8wIMNKYA7HYAEI7f849/VV8Qx
; dAcdzDQGSAGBQ2YYCBUN/zQ0IfzcNyE4/67Nmdr2Gg8jqvju9iqnepUOvLTy8XYwu+qI+WFozeLcqB
; /mV/7fM0vGJo8vTKNgC2BbNMNDf4z63KfqzwcAUSXgAELydJhiarcolyD8WWjBAsRfonTh+EVQPMDD
; Z3zzkbQLRn2BMr2vBt+PZgT+L+b3tKuEPOYS0Y86ADsNgPiB0QwP8dE6a1gPIKBGgEEgkkEYIuLv+6
; pICiG+nAdx8wwP41vhQO1+FsDjOQQcpHFQUMEn00vbPkHPC/fe5c0v/t9JByCJaBSQXCCRMAC61xfL
; c0N5nHHmTwACRgphroTeH3R+m6LiNwKIAPYTYAvACToeAzyei3q+buD7hocv7YzmfxL9ftH9f/w/Ap
; AuFwHvd/CRCwTA9urhvjQXzfAQHfh/X1wyzjeHUpPFDAMhKgUsqKGCktdCZIyiER0T0b6hI0CHSvIY
; sAIeDQ2oqOCT36cFS2eM+mF+DzoA99aN8KkYTLAAjGZ4iI5tlcN6MIGYwhdXTPBwCEKqItSFrU9IiQ
; 41vBDMMrAJSG694rnHgRVoCTheNfAR9QIf/4/I+5mgfiSgjzal/h8dMR316S0AtjkAW6uiCg65Mcqp
; 39NOfQgCUEDycS86OF5ykAAKaRmpIR3Mr/roODXJ37MwBiBfC+B9x4AHvF838KV+33gf+WJ6n3LwPb
; 5wjE+/HJ4zypvfXc70Hp5zh88HpgqY+oGtsUtmaA2nKj1EnygRinQ+QIhCoYQcQPPVoIbfCH7hqyFN
; g2kVjN7UBvC+FcDj+Sgof8+5vnxfKXxPL05TL1Q/jgT121s7wvt+mN+XVk70QYgAjL7gEBsA+HTzWA
; +EBdAroVfD8R4a4PlqCE4AyvuG6yZligh0VE/4/ZV1ublNF6hPyHw+wYfJBz5MLz2A3fNG+eCDwGN3
; bQqf9/9CGsYCGFVwiAyCD7qQUaLnDYBAct4eHsbcN/Qgrp5YAiJq900LXlA9mVxgfmF5Ch+RLgEHSz
; JPLUzhOzJnlDe3pF52hRJcex8Ats2KiekhMeaO+Vw35lcBiIDjZ4DUIXVEFb+8UiBOzBUxRMtfC/C9
; HPxHD9596Tmf9wHHOB/xngq5PlbCYXqJfIl4FXTsNPAVAQQ+KiMzbovrRq754f0/F4CkgOWKB3Tk5g
; hMng3H2WUpiOcDiKxks4qIqS0q3pcCzM+Fc1mfDwBRQuDrIthwvt/++pGDApDfOSriuLYH6ne6OTW/
; 8v3OBx/trFer1DzrQCnPBVXU8/EPvxICFe/nrZiQKV56ntTfE3z4fJTbjjn4jjr4jjSlkW6Hg4/cn8
; pvPCeDUABWlQI447Zohq/ZwdZpJH/PuAS0DTwEIKaS/JwgRSkB6EwAEbAA8UshUCHA8H5eUFCBB8T+
; PO7vFXCQ73sy/H4wmF5SL6gfAOKXktS2AGJ2iwAC5ac//en6ijiuvTFn9I3dAHjWQZJFvAFA1M9Co4
; OgARgBBLAwzdY/LFXPXPWeMvDJ7PIY5yHq3RfgIwmNiv6ytSq58HBvAKmEbDcAciyecWdy8803d1fE
; cW2NrTNv6wEoqRg+HUr2QujLOy1z6QIFwCFq5ZaEMX/3dIieLYTPG/ieEXzAu7AUviPB5wM+zC55P4
; KQF9zfU0Omm/pkwQT3BeD9DdOTtWvXJlOmTIk7KlwLA5M1evTonr1Nd3k1Q7WU61NtVo0BjwXwMJlE
; q0qfPBYgPB1MsgIU5fekfFJQns85jnmfL+10wezurR3pc35UPTC9/A2+I2pYLhWTAjisBECArK+vTx
; 566KFk8eLF0SRfzQNTNXXq1IQDMGhAkPoRufIzqRJAAJqTC9LyGHk64OHgd2ACTs7xtFHBcwFAqd+T
; vsR2Z3YeTOyhkGze68yuAg4dgIc5lj+oakgRwLYAX3u4nV89PZk9e3aydOnS5P77748m+WocFr55My
; d5ePD/XgyRrFqj1Jen6gTQYTaBh+PRAOFJByFwPe3ziGN7KeDpDMBc/ajtdoY+vxS+ERlIgMZ9KCOA
; kpKxgJYDUMfKmklJTU2NP+bMmZNs3Lgxufvuu3uiGl4Fw4JXBBBz+2JQP9sa9WToTBF4+GzAQ8qEA5
; gwx6dCNQPolLB+NuT7ML9PGvObJ5tTdWsPrfaYUKACxj0OOOAjMs5rwsOzlqzWqrwSYgHcWHNnUltb
; m0HY2NiYtLS0JMuWLYtqeCVHOfg47q8Z71Qu9f+s+fXRr08UpxUK4CNJ7I/G9EhBHOXVEdOKWgrA50
; 3CWQqo4EO+395QalOXs8prQEZAAnj6f/vrbvf+YQbgrPIAAjLQccyfPz9ZtWpVUldX539et25dMm3a
; tKiGl3P0BZ6OB2ZP8JCo66WofvLZjgSfzR5dAUBUUAp4JgDo+/tCEHO6pNFgtAe3IzQaoH7A1FKZHq
; ggkGGagZTzc6CGu4wfKLUsZ4YX1MxIVq5cmSxfvtzDhxLiF65ZsyY5depUcu+990Y1vBxjIPg4ds8Z
; l+X/lED2jaFAs/DOEp8NcwgUOoAQM4wCngoKSE7whdDEAIBnlqTJ6ycCzJxLbfaoHwq2zYG3tfI2fy
; sTzONUReRr8r9saa7NAlhQwQ0LZvloGOjmzp3rj7a2tuThhx/2QC5ZsiR54IEHEjIAFXFcmsHk9gfe
; zJkz/YdwsHlq6v+FCBhw0rb4sZliyfxiEg+4o7MMgI8FAPNuGlVRcgDl/wEW5rc9BBMuD8ku+R7CVg
; Ho/EPO/2iIuLkAtDBJyzP7MsOra6d4P5CDdMzevXu96lk1XL16dbJ9+/YYoHzcYzCqR3S4fv36ZMWK
; FR4MYFH1I1M/D0xojwrmtzMkjDk6MwBTH5AAwwJ43gIYfMmTZpklagYs26pS+DYHCAVghwUwvIYOvz
; Apj4QViBTNML8vXLjQR8Bbt271agiMKGFTU5P3C/ERuY85ANJokj+GMRj4iAbJkT344IP+gwC28wHA
; VP3GevV7LLTFP2rM74GGtFGgN4CjPWAonQXwnFFApWCOyp9z5hdQUL0SAB1Uu0IKpisACOACV36gQC
; tnhoER1aMqItBQvebmZu8bcgHyuyJlwEQR3fxENbyYMRjwMD8bNmxI7rvvPu8LERUuq6/05vZ8aD44
; t7x0UdCxkHoBBMwm4BQB5PHjIQ8oAJ8zAPp1Hs1pJYXnATPmdWfY52VbZWp6LYC7DYBHA4DHgh+ofG
; B7AcCiCi5pqPbKB1zz5s3zFxs/Ax5AooQ2XcPPABvV8COOwcDHZGNqiAKZ5EWLFnkg722ozGAhagVG
; IHosJJ6lfoca83ot8HT0BeDitNtFa0osgPInu/wyy5FpMrmyN4CAtDvkALuMD3gstOnbQKQXgEYFV8
; 2e7AFcsGCBf8/c8p4BUAfq2NDQkEHIfczTI4884n3Dijj6Hqrj9gferFmzvK+H2UH1MEFyzvGRHmhu
; LPHX1KNHZYMP3KpfZwmAI9McHYC455wwClgC4LK8lnwyKCrnAqLtVcOCAqYQ5gAO9+kZAXi0KS/95Y
; FIaSqmNYPQNCY0TvdmlYgX8Di4EIHOQsj9MsmkbVBAoMRaxHpyH2OwqscHwBVNtIvqMdHyh5jkw82T
; s6Sxym6+NR74QqeK1M8CuN8COHeUD1asAp4NucBe63zn5v5fawCwpTL3Az2A+G99AEjEbQMRRcKcq7
; Vghrc0TPQAMQ8ooSDkfWOKNQ+qlpCk5rlWDYmcaWyIJtmMgeCbMWOGnziiP9IMBB2abCYYRZD/cyQA
; aPN+JxfkkW+qfnn6RT5gBuCcAoChPxCYnzPn9UstQzKbv2834MgPFIAAtKc2B1x5QA/gnBxg25RQBF
; BlPWDjveLvCkLeN7dAyH1YBeYI6Hi+DVBkKTDh1326ZrDpFa5krnxUD8cb06ukLBPK1Y5Tzq1A8eoX
; Wq6yPr2m3urXUTDBmETAOLkgBfApdUqHhoSzoZvm8bDaDWDl//UF4A6vgL0B1GvqLADYSwFn5QDKx+
; MAQn4XhNzHXAGgjYgFHXOk+/l59+7d3kRfl2o4GPiYYCJc+XyCjsnbsmWLv8qtAqyeN9v37slP861S
; 8/OyW7o4KFU/m/8Dvo5QJvMAhjrwEwbAL3o/cFzJNmvHTDWjLUSwrcYP9AA6EFFH/Dwp7JGmvPsm7a
; C5I9sttd2cJ4dweKaCSxurMwiZD9SQ+QAw3BPrG1qTzPN5niwGKSvOQyBDIEfD65BUQ94UsHGrnwcC
; j4kFOnJ73OLryeRoUpk8JpzJ04RvXtnsATzrI9/QKKBG0TK+Xw5gqoKq03aHxlSrgN4PZAVd6Kbm3E
; fDRpNqPlDwYAHEFwSs/f0AeLAh3yPG15GrigDmZnht/TQPjVSQOcEq4Bfb+eGWOWPuuB8ImSfA08Us
; hdT9Qy5AGQxsxQM/Bqg4MLlKKciMaEKletxHTZTnH1o4KetW8VWK+aNLym5F388CqCpFLwBDZ/TTwQ
; 98NqR1tM+fTUDraA2BCAACYlYHzgBMzXCuymlrVnt1vkKuJSipbdFqCyU55oj3DYhchLgp8gH1s6Jh
; q5AEH/zOYzzPQsh9KCMNr0OinvxR4aOOi0llEpgofmZCZVJ0VSviY/L4GRPt0y8O1mPLpmVbYpSon4
; KPMupnIbQ5QK0P8QA2h/b8pWP9KrunmtOSXtoBk9Zy+wKwJauCBAAb1XeYvy41sQpArQ8pB+CautQv
; 5n1z0WkuNE/8juUQaMwZkAIWfyfgpHzF+7AspGuu+gClvxf3yU9+st7CNXHixGTkyJF9wsebxtQyqc
; CnqI0J4uqVyVGei0kFUBxumSLO8UxYw/FU+C6OrOwWgo++4NOhOm0OYKqAnE81Ye12dSJUQDw4hQSy
; /ED8vxZTBSFf6BXQNL9mANbmAO4wALZYP3BWmorhYuOi4z0DmuZHIKpvUKrH48wZjxeBkxoWKyh8Fl
; dlBcUqW39SDXSDNblcsUwqvgmTpsmQryenWwEHPo9ygPog7muqzpZCquG0e17uZ1kAO8Kh8pvvhqlP
; 4Tg2N01C2xVyHkB3+0w4P/dxfl8BqR3Zq4ZrAfRluLAX4KEA4OEAoX1dAllJ59Y+AGxpmpxs2rQpi4
; CVluGClHvCPBHd4tcBn42IywGnIIXz2fu4+K+qenJfZrX44gZjfnmDSL0qGkyo1E3+jQVRHcAqxvM7
; k83PPgKcXxvW+uYtV0r02sqH/D1b/5VpPlwGQK0X1lJNVVY4vyJg3yxgAQyByNYA4J7avBU/U0ADoJ
; Zvqo0/A7Cytxnm3MwDpTVyo0pKAxXAkIIBPFwZVYiKNWIBZ0t2Ur5yaoil4XxXTA0HA5Re3GArGkwe
; V5fquEqx8KaVXrAlJlSSgwniMU2grtyWhTM9gFrvobqvjX7V+dIRar8WwDQCviNbkGQB1AHcT4fkNu
; c/GNInbdWl9VsLIL8TYHQGEy8FPByWAlgAU18yB3BbGQC55f1jOQANEAGPeQASLmpuNZ82DVMEzipj
; 0Q+0zwVCPi/+32Vfn3wxkWxfR1VVlVe71tZWb0YAT5PEhNqUgd44SojJ1ZUpH4cPgfv4mdtOFwHbzS
; DV9dLb/JYBsDE1j0fDhkInF6QAPmYAfDz0BnLouz46QwqmzcBRBJDH9oYUTDkAD5plnApmtB44rSnn
; Zlj/AwXUhcic0SMIeFzQclU0N8WEtLpn+B2o8PMsfMw/55Fvac/BuVUEuOQmeTCNAR/l4A0RtZGv4k
; pC+fhdcq8I15oATCvPF2yK9GR61ZbE4wcXTjbmV1WGAQBsyDtgbARsd0l4Iqz91WJ1rYR7NNSABU3f
; AOZJ6LIAageF2hxA5fy2hZb+lirbnDAsWbckTaswJwBIoIESMp9KUSnoUDRsIeM+nr9t27bkyJEjHk
; J1Wnd0dCQHDhzwF73yiPIN1XUNhJd8Dcpgg4iBjunTp/sXC0hcqTjHSpby5qhocKXZCWJiAVSlI8HJ
; 70yqUjCK9jiP4NAajTTPdkdp7bcEwJElbfhdJgIWgFLAxwN0gKiFSDwXiMu1UG03AO6o7gfA4Bp0GA
; Bt5SMF8DbvC1oAlzbWZKVJLmb5gcwDSmirIAo61LqPj0hN/cyZM8nBgwez5gbOtWPHjmTXrl1+7rm4
; rb+o+rHMPedRIHpJ1PCGG27oHjt27N+serwx5fYADWCU15O/QY5KxXMmi8DEdnjI9DLJ/L18QP6WSe
; d/PBlMpV3ve7iX/5d3vngA6w2AWRNCan4F4OPhyH9PIef8nGdHdXkAW2flAO43AB42AB4qATD3AaWC
; qikrGNF5ec+4MFzUgGBTMPysKpKFkLQKqsb9gIcbBEz8Tqf1vn37/M+cj/PzmADkfv6eW/5Puc/6E5
; /4RH3Fxz3I540aNSq5GDUEHiaIyUC2bTmIN1iMcnnjVDS41X3yWeTXCEJVAgAVdV3lasAyjap8oH7F
; xlN1vdgG1INB/YopmCKAVhXTKki6Cq4/ALeFOrCqIFYBu0oAzLfqyDaq1OImqWAww+QBN2/enKWfVM
; +1TQkcwIJJZu643b9/f3L06FFvdpXgRxToLsIy8VlxcdsABQj5W31W/N1AQeglGe7kPYNVQy0OKtZx
; BZH8PaUO1Men9nKbuyp2u8j88jOqh2r61nQHoN0M/EjY7aCrjP9XooAFKNLF6L0BFHSCUEloAoe2gQ
; Cs6R/AzgKAfIF1S/ApSwAMa4wxg8ytun8U3SoyFoDqhGZeuagPHTrkTayCF8xwd3e332FBnTJKhfEZ
; qcyHie5L9S4bgAxM8kBKqAgKkwp81nnlzTERgtA2SDJRxZCf3JMmU8AyKfiQWgGmKPDBpXOzNbpqcc
; p8rCKAdSmAdg2ItuVQDdgC6I8A38ngH/o2fACsHVESfPQGcJgHcJ8B8HAZAPcXFFDbtJF+UUvX1mWN
; HjytgmM+bQVEB/dLuVC25557zvt1fCbMGRcuvxNsqHXL5v3kfwu8wcDHUXE5Rl9RMekVzCG+ntRPV6
; TNRyk9IKgAj98V/Vow+VvOJXMhU8L/0NWvmui+VU35CrXQ5t5lnPzBAHi0HwCleicyAPM2rHLwWQB3
; DqCAB8zuqRmAlTmAG5trk02La/2FB3DF9JM1v0rW79y50/t5586d8yqnvwM2ghQCP86nMqfcI86HgK
; CIiAD39Qfd+PHjs9uKyzFuvfXWHlTQKiEvkqsLmHCMbfTEG+JKKtYfUS2usr5KRAKWiQE6rlTOL3PD
; 8zSZPL51wcxsR3oFH12F9qssAAnbo/UGcFS2P2A5AI+HPQSV5Par2QKArX0AiJJJATv7AdDvoGq+vH
; qbiXq5sBW8yXdWkl7qp7ovcwF8XLinT5/2gQbP5yLF93v++ee9i8PzbNkNcPk/uDTcX11d/ZH8/cvW
; PUNQIn8QCHnBXEkAyJtUbo6JKeb3lNAEJOvUFnNUcqzl/zExmFylFziX0g3cD+D750/Kym9qcVJury
; yARgF9d8qc0i6YEgCD+T0emhuU5BaArf0BWDmszzRMlwmO9pm9BLcH31HnXD631iuVtuNg7gShAORx
; fDzyd+fPn/edzopYuVj5nMjd8RlxDq0LkWWR6vE8YB4Atkz5dAwfPvzyVkeUogESnFjekC2jFdu/lf
; xEyYoFb3631Q8bKTMxMi/aFw+V5X4loPkwOlwSWvk/fbiHCivfOoz6CUDbHtUngCEAOR42slSHDefe
; HRYitfZhhgcDYEdhM8sigKsWprVu+X4KIhTYcYES4eLrPfHEE1l7mp17/kaui614oIr4hJy7srLyol
; JtAPmZz3ymu+JyD9RQJhkVAhhrTlXYVqMjhyajWJNU46QmDfMqh1sAyifkygVC+2HsnT8xy/+VUz8L
; 4D5jgi2AxRygB3CB9o8e3QtAleEuBsBiCkYAKqm9NaRd+Hlt/d0eKObE+n+KWplL/D1SWNZftguR5N
; 7YKFmgqtFgINCKqgd4t9xyy6XJ/32UITXkikLm7ZXHfbxBe+UJuOJWEvxs6752oTWKx5WqLDzPA0Jl
; 8R+ZNyPf78+o30AAdhYAPN4HgOot1FJKvxVHQ1qGazXNAv0CWN8bQKVg/F7SfQC4xgEo8ysIMZVYgz
; 179iTt7e3eBVKaygZ8SoHZeVbzrnx11ln3B96YMWOSm266qad4XBHV62vYhLWtISq9oppksROD+5SW
; 0QIkRXcKQphc/EwtvbR5Lx5jMjfNnZFvEN54eyl88v8CfDpsHrAvH/CUAfDYvHwppfaC0VYcfwuA+w
; OAflVcWBG3NeT9OMeDc2dmygc0mFwU78KFC756QVJapTa7JkQlNNtVxOeBZWGu+0sqX7bc3sc9FKDw
; Jgn1bX6pr0ZIJkfZdquQQIe5VelOZlgqKFD5X3wISrtoxVuvdb91qanjw95bZ0txdwQVLK0Dn1qQf3
; 2D9pSxSykPhDrwQAC2mUXpWdWlMd8YSSmYXWE/6ZaqfC0JMG5cWO0zBlyARLUvvfSSj2aPHTvm58hC
; p3q55sz6gES/qJ/EoAjbiBEjfDChoOKKm9aLHZhk1BBp1zLBmkIjpNIyQKQVWlJDdVyghqio/BZBqN
; KTzYUx4dvWrUja5002Dae9TS8fNAcQpirYe0csW/E4ZSLgY3NLV7JpMbpvFOjDD5QZ1bejA/sh4yJk
; EXDIAbaF81kAV9VO8VULVO/48ePJ4cOHvflV6sUuVSi3MAk3RY2r3N9fKuWaVL1yw6ZrmIBiz5nSKw
; pMrH+i8p2uatV+VWxXJwwQcrUrEJF5anlgZbKl/q4A2givdv4rssLXZO0KBz9LCbUehCBDyeaT/QDo
; d0M1ALb0AyAg7TKr4gRgZ9kI2AIY/MD1a5OzZ8/61MrLL7/sfV+bzFdHeDGlxf1q9lWmYaAg48Ybb+
; yuGEpDAYqiLkVo1tdTRIw5UXpFeUJbD1ZEbNux1MQKgIJQ7Ub4OytcDm39iuZkkzNj650v9fD8yuSh
; pnuSLa6y0PHg0mRr48Skdc4kDyQQyg88YUyxvsRG7f36LhA1ImzrD8CwR0y6MH1EFnmrOyczv8H/Uw
; CyOawn5u9PHNjtTS4AMi/K6WmPQM2NdsqSP41bo3LdkPP1PsqwAQpKyBVs/UDAYULVFGkDFLv9Rrmm
; BJlztQ8JQiadcxIlcl6tJ+bDI1lLLVRLQPEhidS3r1+d7HYm/JjpCTxpImD5ftreoxeAVeUT0ZvDDq
; n2O0Kkfvb7RNR8wPMfuedWr4LdrQ8mJ06cyPrwrBuidqw6s0WvNiRSHZc5u67hs0MmGd+QCWXiUCsi
; WbVXFRPS8g2LTQl2RZhtTJUpQmH5IFBVbeGBee7q6vL34xNp2zKcc8y+mhyAsHt+2pZfBFCNBPhy+0
; InTNYqVVDBVt/J4oKIGbcmG2rvSjbXjU+2NYzPovC95uu6ML0oHuDdXzUmaVkxz6dXeL1a/aecn70Y
; sRi8H0Gpsh3vbyDlu6YDjYsdClBQQxxpPnwbpKjVvugvSg1tMFKMiAUhJTolsXkcyPggT548WaKGAI
; ep1vpXJcv5EI+G/QFlfu3GloeznQxGetWSqbQAqg68YUF11uApBeb3e5tmJ8ubanySma021rhjccOs
; LLDifaj5wC46V0eRXafB3NBmpR0SaAyJqtfPsAGKasnF/KBN19iEtF0XUmcWYKszGmVV1we/A1ZnZ6
; dXONSNdI2iQu7zMLif1QmsgGnbolmZL3g85ACPmC+10bccWQDlB2pnq/XzqnzaBMBVv1V+lP8hl0Fu
; g5TO7vmix9VoqoBMmQHtCyOXg/MOFGhcVQnkKzkUoGCSUZ1y+UEFKMU0g1UFJasBSUqopQAsuCmqIT
; 6gml5RQw6UjwsBCHUoIMnXF+dVFvKHasXaahcOhWPj7HH+/FowpHXPairQ+l2lTPS69bh9f+oo4jEb
; mPF6CTR4r4Op48YNKcuMYj25uDjJ1pNtRKzsvjYyklIob0hLktbL6rzcAgMfPErJ41ImwSgI+Xnroq
; rw7Zkyv6NC/i5NQqsTxqZMtJvBygXp3n2CDqVHfW09V718ciMUWNlAS8qn+9RVjrnV6xyoeyXCN4hh
; 0zWoWbk+QVvnVCe11ppICQEIf4/oUKqiDl+cdZkvDlQPH1AtSDq0d56HdN49ee7PfKtSR/imy7xqkb
; fMr6m724PFeVTy0g5VKKE6fKTwNsCwqi43os5sQs55cR20dmOgvr0I3kcYxXpyMRhRb5v8HvmD+pAJ
; PmgN0xYVfFjcD0haSWfTNWppQhUBzm5hhtkGTM6xwdWZS9aWNNyefbuR3QMQCFfX5Y0D+n/Fqg0XCQ
; GYAiu7zkV5TvVQ6nXqgtOOYUOyjns1DBugqJO3WClByawaAhHrG7QCTArCh6UtyWykbBs6dQAF7UxK
; CdnuE0z3yvl1SatLoaiktzvsB7P5njRpvKp2apb0lV+nQykmmzbiPiDk3HVmh1cpsN2ShNfHBQLMgj
; KmVy7xULqGlAImS19RqiZXfbDcR1JZyqiIWM0NUhZ1aQtEPkSgEIBaYYeJJCDS/fLfUB/fSewqK9vn
; Tkk2N0xIHnaBxn2zp5bApr9R1cbuX6PtNKzLgKsA9HY3A0HGcwCUi1BdQFH1LuNQgIIa8iFgSq05Jt
; BARWwxng9fvXHl0jUWCA5tYSZgtMiJgEFpEYEF1MX7pXrWpxPgtmVe0OnCqTPrdzkfvqjdWJzHUXrg
; l6m+7uq4V8tQgMKHAhwoFCaXD18RMR80KqUPUfkyC6EUUiqk3jipoQWI+4FCPYgoJABq27hiFUb3WZ
; 9OAYbd19B+nYI6vdVGxfl5f7xGJZXVYBBV7woPG6CQ3LXJa5lcrYMoNjDY8hUfOLAAlMycYFFOUIBq
; gT1Nn3b7C5v8tsAp8LDQq/lCr8Gu9uOcdncInsvr4v3xOgZaEhnhuwJDAQrpB3VKa08Z22FtQZRPpd
; 2ftJt8MfXBc1Sq004N/A/tuVc06+WAU4BhFU/AWXOsC0T/lwP1U/SOmsdA4yodClD4EPHfimuO7RJQ
; CyEwSXFsG5OCERuJkqTWskYFBqiTuk9sY0QROFu7Lr4GuzmTXq/2cImqdw2NYsMrH2K5Cgq3qIpKfX
; bTRrvtrzbGVBJa/pftuZOCYpaLG6aXA87ufWPr2VJC+X3aXmOg7pUYaFyFo9jwWqwn65sliyvytG7Z
; rqXQ9w5bkGw7mIVIXdt9AWej9XIr09Q4odJjVL1reJSrJwON1prUFdYcy1dU5MvzqX4oYCnuKFpsjp
; XCagOl/rYXsT2NUl5eFwGI8oURviEyZJKBiKqGXfyuOqptWwcSVMh+G1N/q/fK9SoClr59yP69zLr1
; 9QBOm3Ty/waq41727S6uwPh/Xksp4OeGPHMAAAAASUVORK5CYII=
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; rip gcode lol

; filament used [mm] = 34275.96
; filament used [cm3] = 82.44
; filament used [g] = 102.23
; filament cost = 2.60
; total filament used [g] = 102.23
; total filament cost = 2.60
; estimated printing time (normal mode) = 13h 5m 14s
; estimated printing time (silent mode) = 13h 9m 5s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 5
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600\nG1 E0.4 F1500 ; prime after color change
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Generic PLA"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 15%
; fill_pattern = lightning
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.15
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{initial_filament_type}_{printer_model}_{print_time}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 45
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.15mm QUALITY @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.11.0 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\n{if filament_settings_id[initial_tool]=~/.*Prusament PA11.*/}\nG1 Z0.3 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E9 F1000 ; intro line\n{else}\nG1 Z0.2 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\n{endif}\nG92 E0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 12
; thumbnails = 160x120
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 8
; top_solid_min_thickness = 0.7
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 0.4
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
